import React, {useState} from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link } from "react-router-dom";

import {veryfyCodeLog} from "../Store/AuthSlice";
import {jwtDecode} from "jwt-decode";

const Form2FA = () => {

    const dispatch = useDispatch();

    // const handleSubmit = (event) => {
    //     event.preventDefault();
    //     const email = event.target.email.value;
    //     dispatch(forgotPassword({email: email, data: email}));
    // }


    const [code,setCode] = useState(null)
    const  token = localStorage.getItem('user')
    const decode = jwtDecode(token)
    const  email  = decode.sub


    const handleSubmit =async (event) => {

         event.preventDefault();

         const validateCodeDTO = {
          email : email ,
             code: code
         }

  console.log(validateCodeDTO)
        sendCode( {validateCodeDTO})
         // if (response.payload.valid === true) {
         //  window.location.href('/dashboard')
         //     console.log("estoy en el condicional")
         // }
     }

 const  sendCode  = ({validateCodeDTO}) =>{
try {
    console.log("esto es el validateDTO")
    console.log(validateCodeDTO)
    const response = dispatch(veryfyCodeLog(validateCodeDTO))
    console.log(response)
}catch (e) {
   throw e
}
    }


    return(
        <div className="min-h-screen flex items-center justify-center">
            <div className="max-w-md w-full p-6 bg-white rounded-lg shadow-lg">

                <h1 className="text-2xl font-semibold text-center text-gray-500 mt-8 mb-6">Two-step authentication</h1>
                <p className="text-sm text-gray-600 text-center mt-8 mb-6">Enter the code generated by Google Authenticator</p>
                <form onSubmit={handleSubmit}>
                    <div className="mb-6">
                        <label htmlFor="email" className="block mb-2 text-sm text-gray-600">Code</label>
                        <input type="number" id="number" name="code"  onChange={(e)=>setCode(e.target.value)} className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required/>
                    </div>
                    <button type="submit" className="w-32 bg-gradient-to-r from-blue-400 to-blue-600 text-white py-2 rounded-lg mx-auto block focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500 mt-4 mb-4">validate</button>
                </form>
                <div className="text-center">
                    <p className="text-sm">Volver a <Link to={"/"} className="text-blue-600 hover:underline">Iniciar sesión</Link></p>
                </div>
                <p className="text-xs text-gray-600 text-center mt-8">&copy; 2024 Business solutions</p>
            </div>
        </div>
    );
}
export default Form2FA;
